name: radegs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile=0.8.1
  - python=3.9
  - pip=22.3.1
  - pytorch=2.3.1
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - tqdm
  - pip:
    - ./submodules/diff-gaussian-rasterization
    - ./submodules/simple-knn
